name: Debug SSH Connection

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: |
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "SSH Key present: ${{ secrets.EC2_SSH_KEY != '' && 'YES' || 'NO' }}"
          
      - name: Setup SSH key file
        run: |
          mkdir -p ~/.ssh
          # Create the key file
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          echo "Key file created"
          ls -la ~/.ssh/
          
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem -v ubuntu@${{ secrets.EC2_HOST }} "echo 'SSH test successful'" || echo "SSH failed"