name: Test Secrets

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Repository Secrets
        run: |
          echo "Host: ${{ secrets.EC2_HOST }}"
          echo "Key length: ${#secrets.EC2_SSH_KEY}}"