name: Test Secrets

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Repository Secrets
        run: |
          echo "Testing secrets..."
          if [ -n "${{ secrets.EC2_HOST }}" ]; then
            echo "✅ EC2_HOST is set (length: ${#{{ secrets.EC2_HOST }}})"
          else
            echo "❌ EC2_HOST is not set"
          fi
          
          if [ -n "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "✅ EC2_SSH_KEY is set"
            echo "Key preview: ${ {{ secrets.EC2_SSH_KEY }}:0:50 }..."
          else
            echo "❌ EC2_SSH_KEY is not set"
          fi